name: my-better-t-app

services:
  postgres:
    image: postgres:16-alpine
    container_name: my-better-t-app-postgres
    environment:
      POSTGRES_DB: my_better_t_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - my_better_t_app_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  my_better_t_app_postgres_data:
